name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
        env:
          NODE_ENV: prod
          REACT_APP_SENTRY_RELEASE: ${{ github.sha }}
      - name: Deploy
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: ./.github/workflows/deploy-frontend.sh

  deploy-firebase:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firebase/functions
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: ../../.github/workflows/deploy-firebase.sh
